-- Insert data into the microchipvendor table (Hardcoded)
INSERT INTO microchipvendor (microchip_vendorName) VALUES
('AKC Reunite'),
('AVID'),
('Banfield TruPaws'),
('BarkCode Solutions'),
('CritterID Systems'),
('Datamars'),
('Destron Fearing'),
('FurSecure ID'),
('FurTrack Microchips'),
('FurryTag Systems'),
('HomeAgain'),
('LifeChip'),
('PawID Technologies'),
('PawPrint ID'),
('PawTech Microchips'),
('PetGuardian Chips'),
('PetLink'),
('PetSafe Chips'),
('Trovan'),
('24PetWatch');
